### ISSUE TITLE
Extension icon doesn't match icon in Weather app

### ISSUE THREAD

**Issue by kirill-gr** [somepaulo/GNOME-Shell-extension-Weather-or-Not#11]
## Distro Name & Version
Ubuntu 23.10

## GNOME Shell Version
45.2

## Other Installed Extensions
N/A

## Expected Behavior
Icon in the extension shows actual weather conditions reported by the Weather app

## Current Behavior
Most of the time the extension shows the "sun" icon. On few short intervals though it was showing a correct icon.
![image](https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/assets/5472920/1c92df8e-8b39-4d47-a113-187a2c3322f5)

**Comment by somepaulo** [comment]
This is a known [issue](https://gitlab.gnome.org/GNOME/gnome-weather/-/issues/252) with the underlying workings of Gnome Shell.  
The extension gets its info from the widget in the notifications centre, which doesn't sync well with the Weather app.
