### ISSUE TITLE
[Bug] Need an option to remove the gap between DateTimeClock and Weather box

### ISSUE THREAD

**Issue by rr1231234** [somepaulo/GNOME-Shell-extension-Weather-or-Not#16]
![Screenshot from 2024-05-16 11-49-57](https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/assets/92568853/ff54778a-4c67-4e44-9561-b94c439c2b2f)

Position: Clock right centered

**Comment by somepaulo** [comment]
The gap is there for a reason: the clock and the weather pill are separate instances, and the clock has a space reserved for the notification dot. Being separate instances is what enables the click on the weather widget to open the Weather app, not the notification panel.  
If you want the weather inside the clock (without the ability to open the Weather app), you can use the [Weather O'Clock](https://extensions.gnome.org/extension/5470/weather-oclock/) extension.  
Alternatively, you can use the [Unite](https://github.com/hardpixel/unite-shell) extension (from GitHub), and set the option to reduce panel item spacing.
