### ISSUE TITLE
second click should CLOSE the window "GNOME Weather" instead of opening another window

### ISSUE THREAD

**Issue by pastylka** [somepaulo/GNOME-Shell-extension-Weather-or-Not#18]
this solution is not elegant, but it works

// _indicator.connect('button-press-event', () => GLib.spawn_command_line_async('gapplication launch org.gnome.Weather'));

_indicator.connect('button-press-event', () => GLib.spawn_command_line_async('bash -c "[ $(ps xc | grep org.gnome.Weath | wc -l) != 0 ] && pkill org.gnome.Weath && exit; gapplication launch org.gnome.Weather"'));

**Comment by somepaulo** [comment]
I'm not comfortable with killing the app from within the extension (and I'm not sure it would pass the review).
Anyway, it's now solved in #14, and just brings the window to front if it's open instead of opening a new one.
