### ISSUE TITLE
Blinking whenever the app is updated

### ISSUE THREAD

**Issue by GuillaumeAmat** [somepaulo/GNOME-Shell-extension-Weather-or-Not#3]
Hey, thank you very much for this fork/effort :pray: 

By any chance, do you think you could have a look into this bug, which is also present in your fork?

https://github.com/JasonLG1979/gnome-shell-extension-weather-in-the-clock/issues/23

**Comment by somepaulo** [comment]
That's inherent to how the indicator gets the weather info - it waits for an active network connection, and then listens to Gnome's weather API and updates the content of the indicator on change. That entails making and breaking connections and some more magic, which, I guess, is causing the info to disappear on update and/or network connection/disconnection. Whether seamless updates are possible at all, I don't know.

I didn't write the part of the code that does that, and GJS/JS is not my strongest skill, but you're more than welcome to have a look and suggest a solution or make a PR.

**Comment by somepaulo** [comment]
I've looked closer into it, and, as far as I can understand, the whole issue is in this line 159:
`this._pushSignal(this, 'destroy', this._onDestroy.bind(this));`
When the weather info gets updated, the indicator's inner components (icon and label) are destroyed and rebuilt again with the new info. While this happens, nothing is visible. So we need either some new code to display a spinner while the new info is retrieved or rewriting the existing code to keep the old info displayed until the new one is ready and make the switch instantly, like time in the clock.

I really don't have much time to learn how to achieve this, so any contributions are welcome.

**Comment by GuillaumeAmat** [comment]
Hey @somepaulo, thank you very much for the time you've taken answering/investigating my question :pray: 

I'm not a GJS ninja either, but always thought I would contribute to something related to GNOME  at some point (being a long time user).

You've given me a lead to follow, and here it is: https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/pull/4

It was not related to the destroy logic, though, but I'm glad it's fixed now :fire:

**Comment by somepaulo** [comment]
Thank you for your contribution! It's already out on EGO.  
Just for reference, I had to add `clearTimeout(this._weatherUpdateDebounceTimer);` to `_onDestroy()` in order to get it approved.
