### ISSUE TITLE
Blinking indicator (still)

### ISSUE THREAD

**Issue by GuillaumeAmat** [somepaulo/GNOME-Shell-extension-Weather-or-Not#8]
## Distro Name & Version

Fedora 39

## GNOME Shell Version

GNOME 45.2

## Detailed Description

The issue described here https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/issues/3 still exists, unfortunately.

A first fix attempt has been merged (https://github.com/somepaulo/GNOME-Shell-extension-Weather-or-Not/pull/4), but the 500 ms is not enough, apparently. I still experience a blinking status, less often though, but several times a day.

@somepaulo: Would you consider another PR that would increase the debounce time to 10 seconds?

IMHO, it would not hurt the user experience, but rather improve it significantly.

**Comment by somepaulo** [comment]
Increased the timer to 10s as you suggested. Published in latest version 45.1 (13)

**Comment by GuillaumeAmat** [comment]
Awesome, thanks! :heart:
